In [39]:
import numpy as np
seq1='ACAGTAG'
seq2='ACTCG'

In [40]:
matrix=np.zeros((len(seq1)+1,len(seq2)+1))

In [41]:
matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Similarity matrix

In [42]:
s_matrix=np.zeros((len(seq1),len(seq2)))
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if seq1[i]==seq2[j]:
            s_matrix[i][j]=1
        else:     
            s_matrix[i][j]=0
s_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
match_score=1
mismatch_score=0
gap_penalty=-1

In [44]:
def NW_matrix(matrix):
   for i in range(len(seq1)+1):
       matrix[i][0]=i*gap_penalty
   for j in range(len(seq2)+1):
       matrix[0][j]=j*gap_penalty
   for i in range(1,len(seq1)+1):
       for j in range(1,len(seq2)+1):
                matrix[i][j]=max(matrix[i-1][j-1]+s_matrix[i-1][j-1],matrix[i-1][j]+gap_penalty,matrix[i][j-1]+gap_penalty)

   return(matrix)

In [45]:
NW_matrix(matrix)

array([[ 0., -1., -2., -3., -4., -5.],
       [-1.,  1.,  0., -1., -2., -3.],
       [-2.,  0.,  2.,  1.,  0., -1.],
       [-3., -1.,  1.,  2.,  1.,  0.],
       [-4., -2.,  0.,  1.,  2.,  2.],
       [-5., -3., -1.,  1.,  1.,  2.],
       [-6., -4., -2.,  0.,  1.,  1.],
       [-7., -5., -3., -1.,  0.,  2.]])

In [36]:
AlignmentA=""
AlignmentB=""
i=len(seq1)
j=len(seq2)
while (i >0 or j >0):

  if (i > 0 and j > 0 and matrix[i][j] == matrix[i-1][j-1] + s_matrix[i-1][j-1]):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    i=i - 1
    j=j - 1

  elif (i > 0 and matrix[i][j] == matrix[i-1][j] + gap_penalty):
  
    AlignmentA=seq1[i-1] + AlignmentA
    AlignmentB="-" + AlignmentB
    i=i - 1
  
  else:
  
    AlignmentA="-" + AlignmentA
    AlignmentB=seq2[j-1] + AlignmentB
    j=j - 1


In [37]:
AlignmentA

'ACAGTAG'

In [38]:
AlignmentB

'AC--TCG'